# Generated by Django 4.2.1 on 2023-05-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpartner',
            options={'verbose_name': 'Слайд_Партнёр', 'verbose_name_plural': 'Слайд_Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='mainpartnerimg',
            options={'verbose_name': 'Слайд_Партнёр_Фото', 'verbose_name_plural': 'Слайд_Партнёры_Фото'},
        ),
        migrations.AddField(
            model_name='mainpartner',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
