# Generated by Django 4.1.7 on 2023-02-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_vehicletype_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
