# Generated by Django 4.1.7 on 2023-02-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_oiltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='oiltype',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
