# Generated by Django 4.1.7 on 2023-02-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
