# Generated by Django 4.1.7 on 2023-02-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.compound'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oiltype',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.oiltype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='viscosity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.viscosity'),
        ),
    ]
