# Generated by Django 4.1.7 on 2023-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_compound_alter_product_oiltype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='name_m',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
