# Generated by Django 4.1.7 on 2023-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_id_product_code_product_name_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
