# Generated by Django 4.1.7 on 2023-02-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.fuel'),
        ),
    ]
