# Generated by Django 4.1.7 on 2023-03-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_code_alter_product_name_m_and_more'),
        ('shop', '0019_remove_product_quantity_alter_product_code_and_more'),
    ]

    operations = [
    ]
