# Generated by Django 4.1.7 on 2023-03-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_partnerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerimage',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.partner'),
        ),
    ]
