# Generated by Django 4.1.7 on 2023-03-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_partner_describtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='describtion',
            new_name='description',
        ),
    ]
