# Generated by Django 4.1.7 on 2023-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_rename_describtion_partner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
