# Generated by Django 4.1.7 on 2023-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_categoryimage_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fuel',
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('category', models.ManyToManyField(to='shop.category')),
                ('compound', models.ManyToManyField(to='shop.compound')),
                ('fuel', models.ManyToManyField(to='shop.fuel')),
                ('oiltype', models.ManyToManyField(to='shop.oiltype')),
                ('viscosity', models.ManyToManyField(to='shop.viscosity')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.ManyToManyField(to='shop.transmission'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel',
            field=models.ManyToManyField(to='shop.fuel'),
        ),
    ]
