# Generated by Django 4.1.7 on 2023-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_brand_product_description_product_visual_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='compound',
            field=models.ManyToManyField(blank=True, to='shop.compound'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='fuel',
            field=models.ManyToManyField(blank=True, to='shop.fuel'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='viscosity',
            field=models.ManyToManyField(blank=True, to='shop.viscosity'),
        ),
    ]
