# Generated by Django 4.1.7 on 2023-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_transmission_compound_alter_transmission_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visual_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
