# Generated by Django 4.1.7 on 2023-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_product_visual_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fuel',
            field=models.ManyToManyField(blank=True, to='shop.fuel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.ManyToManyField(blank=True, to='shop.transmission'),
        ),
    ]
