# Generated by Django 4.1.7 on 2023-03-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_product_security_pasport_product_tech_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viscosity',
        ),
        migrations.AddField(
            model_name='product',
            name='viscosity',
            field=models.ManyToManyField(blank=True, null=True, to='shop.viscosity'),
        ),
    ]
