# Generated by Django 4.1.7 on 2023-03-12 11:59

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_product_viscosity_product_viscosity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='shop/img/products'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
