# Generated by Django 4.1.7 on 2023-05-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_product_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.compound'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fuel',
            field=models.ManyToManyField(blank=True, default='-', to='shop.fuel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oiltype',
            field=models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.oiltype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.ManyToManyField(blank=True, default='-', to='shop.transmission'),
        ),
        migrations.AlterField(
            model_name='product',
            name='viscosity',
            field=models.ManyToManyField(blank=True, default='-', null=True, to='shop.viscosity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, default='-', null=True),
        ),
    ]
